((LINK "Australia/Sydney" "Australia/ACT")
 (LINK "Australia/Lord_Howe" "Australia/LHI")
 (LINK "Australia/Sydney" "Australia/NSW")
 (LINK "Australia/Darwin" "Australia/North")
 (LINK "Australia/Brisbane" "Australia/Queensland")
 (LINK "Australia/Adelaide" "Australia/South")
 (LINK "Australia/Hobart" "Australia/Tasmania")
 (LINK "Australia/Melbourne" "Australia/Victoria")
 (LINK "Australia/Perth" "Australia/West")
 (LINK "Australia/Broken_Hill" "Australia/Yancowinna")
 (LINK "America/Rio_Branco" "Brazil/Acre")
 (LINK "America/Noronha" "Brazil/DeNoronha")
 (LINK "America/Sao_Paulo" "Brazil/East") (LINK "America/Manaus" "Brazil/West")
 (LINK "Europe/Brussels" "CET") (LINK "America/Chicago" "CST6CDT")
 (LINK "America/Halifax" "Canada/Atlantic")
 (LINK "America/Winnipeg" "Canada/Central")
 (LINK "America/Toronto" "Canada/Eastern")
 (LINK "America/Edmonton" "Canada/Mountain")
 (LINK "America/St_Johns" "Canada/Newfoundland")
 (LINK "America/Vancouver" "Canada/Pacific")
 (LINK "America/Regina" "Canada/Saskatchewan")
 (LINK "America/Whitehorse" "Canada/Yukon")
 (LINK "America/Santiago" "Chile/Continental")
 (LINK "Pacific/Easter" "Chile/EasterIsland") (LINK "America/Havana" "Cuba")
 (LINK "Europe/Athens" "EET") (LINK "America/Panama" "EST")
 (LINK "America/New_York" "EST5EDT") (LINK "Africa/Cairo" "Egypt")
 (LINK "Europe/Dublin" "Eire") (LINK "Etc/GMT" "Etc/GMT+0")
 (LINK "Etc/GMT" "Etc/GMT-0") (LINK "Etc/GMT" "Etc/GMT0")
 (LINK "Etc/GMT" "Etc/Greenwich") (LINK "Etc/UTC" "Etc/UCT")
 (LINK "Etc/UTC" "Etc/Universal") (LINK "Etc/UTC" "Etc/Zulu")
 (LINK "Europe/London" "GB") (LINK "Europe/London" "GB-Eire")
 (LINK "Etc/GMT" "GMT+0") (LINK "Etc/GMT" "GMT-0") (LINK "Etc/GMT" "GMT0")
 (LINK "Etc/GMT" "Greenwich") (LINK "Asia/Hong_Kong" "Hongkong")
 (LINK "Africa/Abidjan" "Iceland") (LINK "Asia/Tehran" "Iran")
 (LINK "Asia/Jerusalem" "Israel") (LINK "America/Jamaica" "Jamaica")
 (LINK "Asia/Tokyo" "Japan") (LINK "Pacific/Kwajalein" "Kwajalein")
 (LINK "Africa/Tripoli" "Libya") (LINK "Europe/Brussels" "MET")
 (LINK "America/Phoenix" "MST") (LINK "America/Denver" "MST7MDT")
 (LINK "America/Tijuana" "Mexico/BajaNorte")
 (LINK "America/Mazatlan" "Mexico/BajaSur")
 (LINK "America/Mexico_City" "Mexico/General") (LINK "Pacific/Auckland" "NZ")
 (LINK "Pacific/Chatham" "NZ-CHAT") (LINK "America/Denver" "Navajo")
 (LINK "Asia/Shanghai" "PRC") (LINK "Europe/Warsaw" "Poland")
 (LINK "Europe/Lisbon" "Portugal") (LINK "Asia/Taipei" "ROC")
 (LINK "Asia/Seoul" "ROK") (LINK "Asia/Singapore" "Singapore")
 (LINK "Europe/Istanbul" "Turkey") (LINK "Etc/UTC" "UCT")
 (LINK "America/Anchorage" "US/Alaska") (LINK "America/Adak" "US/Aleutian")
 (LINK "America/Phoenix" "US/Arizona") (LINK "America/Chicago" "US/Central")
 (LINK "America/Indiana/Indianapolis" "US/East-Indiana")
 (LINK "America/New_York" "US/Eastern") (LINK "Pacific/Honolulu" "US/Hawaii")
 (LINK "America/Indiana/Knox" "US/Indiana-Starke")
 (LINK "America/Detroit" "US/Michigan") (LINK "America/Denver" "US/Mountain")
 (LINK "America/Los_Angeles" "US/Pacific")
 (LINK "Pacific/Pago_Pago" "US/Samoa") (LINK "Etc/UTC" "UTC")
 (LINK "Etc/UTC" "Universal") (LINK "Europe/Moscow" "W-SU")
 (LINK "Etc/UTC" "Zulu")
 (LINK "America/Argentina/Buenos_Aires" "America/Buenos_Aires")
 (LINK "America/Argentina/Catamarca" "America/Catamarca")
 (LINK "America/Argentina/Cordoba" "America/Cordoba")
 (LINK "America/Indiana/Indianapolis" "America/Indianapolis")
 (LINK "America/Argentina/Jujuy" "America/Jujuy")
 (LINK "America/Indiana/Knox" "America/Knox_IN")
 (LINK "America/Kentucky/Louisville" "America/Louisville")
 (LINK "America/Argentina/Mendoza" "America/Mendoza")
 (LINK "America/Puerto_Rico" "America/Virgin")
 (LINK "Pacific/Pago_Pago" "Pacific/Samoa")
 (LINK "Africa/Abidjan" "Africa/Accra")
 (LINK "Africa/Nairobi" "Africa/Addis_Ababa")
 (LINK "Africa/Nairobi" "Africa/Asmara")
 (LINK "Africa/Abidjan" "Africa/Bamako") (LINK "Africa/Lagos" "Africa/Bangui")
 (LINK "Africa/Abidjan" "Africa/Banjul")
 (LINK "Africa/Maputo" "Africa/Blantyre")
 (LINK "Africa/Lagos" "Africa/Brazzaville")
 (LINK "Africa/Maputo" "Africa/Bujumbura")
 (LINK "Africa/Abidjan" "Africa/Conakry")
 (LINK "Africa/Abidjan" "Africa/Dakar")
 (LINK "Africa/Nairobi" "Africa/Dar_es_Salaam")
 (LINK "Africa/Nairobi" "Africa/Djibouti")
 (LINK "Africa/Lagos" "Africa/Douala")
 (LINK "Africa/Abidjan" "Africa/Freetown")
 (LINK "Africa/Maputo" "Africa/Gaborone")
 (LINK "Africa/Maputo" "Africa/Harare")
 (LINK "Africa/Nairobi" "Africa/Kampala")
 (LINK "Africa/Maputo" "Africa/Kigali") (LINK "Africa/Lagos" "Africa/Kinshasa")
 (LINK "Africa/Lagos" "Africa/Libreville")
 (LINK "Africa/Abidjan" "Africa/Lome") (LINK "Africa/Lagos" "Africa/Luanda")
 (LINK "Africa/Maputo" "Africa/Lubumbashi")
 (LINK "Africa/Maputo" "Africa/Lusaka") (LINK "Africa/Lagos" "Africa/Malabo")
 (LINK "Africa/Johannesburg" "Africa/Maseru")
 (LINK "Africa/Johannesburg" "Africa/Mbabane")
 (LINK "Africa/Nairobi" "Africa/Mogadishu")
 (LINK "Africa/Lagos" "Africa/Niamey")
 (LINK "Africa/Abidjan" "Africa/Nouakchott")
 (LINK "Africa/Abidjan" "Africa/Ouagadougou")
 (LINK "Africa/Lagos" "Africa/Porto-Novo")
 (LINK "America/Puerto_Rico" "America/Anguilla")
 (LINK "America/Puerto_Rico" "America/Antigua")
 (LINK "America/Puerto_Rico" "America/Aruba")
 (LINK "America/Panama" "America/Atikokan")
 (LINK "America/Puerto_Rico" "America/Blanc-Sablon")
 (LINK "America/Panama" "America/Cayman")
 (LINK "America/Phoenix" "America/Creston")
 (LINK "America/Puerto_Rico" "America/Curacao")
 (LINK "America/Puerto_Rico" "America/Dominica")
 (LINK "America/Puerto_Rico" "America/Grenada")
 (LINK "America/Puerto_Rico" "America/Guadeloupe")
 (LINK "America/Puerto_Rico" "America/Kralendijk")
 (LINK "America/Puerto_Rico" "America/Lower_Princes")
 (LINK "America/Puerto_Rico" "America/Marigot")
 (LINK "America/Puerto_Rico" "America/Montserrat")
 (LINK "America/Toronto" "America/Nassau")
 (LINK "America/Puerto_Rico" "America/Port_of_Spain")
 (LINK "America/Puerto_Rico" "America/St_Barthelemy")
 (LINK "America/Puerto_Rico" "America/St_Kitts")
 (LINK "America/Puerto_Rico" "America/St_Lucia")
 (LINK "America/Puerto_Rico" "America/St_Thomas")
 (LINK "America/Puerto_Rico" "America/St_Vincent")
 (LINK "America/Puerto_Rico" "America/Tortola")
 (LINK "Pacific/Port_Moresby" "Antarctica/DumontDUrville")
 (LINK "Pacific/Auckland" "Antarctica/McMurdo")
 (LINK "Asia/Riyadh" "Antarctica/Syowa")
 (LINK "Europe/Berlin" "Arctic/Longyearbyen") (LINK "Asia/Riyadh" "Asia/Aden")
 (LINK "Asia/Qatar" "Asia/Bahrain") (LINK "Asia/Kuching" "Asia/Brunei")
 (LINK "Asia/Singapore" "Asia/Kuala_Lumpur") (LINK "Asia/Riyadh" "Asia/Kuwait")
 (LINK "Asia/Dubai" "Asia/Muscat") (LINK "Asia/Bangkok" "Asia/Phnom_Penh")
 (LINK "Asia/Bangkok" "Asia/Vientiane")
 (LINK "Africa/Abidjan" "Atlantic/Reykjavik")
 (LINK "Africa/Abidjan" "Atlantic/St_Helena")
 (LINK "Europe/Brussels" "Europe/Amsterdam")
 (LINK "Europe/Prague" "Europe/Bratislava")
 (LINK "Europe/Zurich" "Europe/Busingen")
 (LINK "Europe/Berlin" "Europe/Copenhagen")
 (LINK "Europe/London" "Europe/Guernsey")
 (LINK "Europe/London" "Europe/Isle_of_Man")
 (LINK "Europe/London" "Europe/Jersey")
 (LINK "Europe/Belgrade" "Europe/Ljubljana")
 (LINK "Europe/Brussels" "Europe/Luxembourg")
 (LINK "Europe/Helsinki" "Europe/Mariehamn")
 (LINK "Europe/Paris" "Europe/Monaco") (LINK "Europe/Berlin" "Europe/Oslo")
 (LINK "Europe/Belgrade" "Europe/Podgorica")
 (LINK "Europe/Rome" "Europe/San_Marino")
 (LINK "Europe/Belgrade" "Europe/Sarajevo")
 (LINK "Europe/Belgrade" "Europe/Skopje")
 (LINK "Europe/Berlin" "Europe/Stockholm")
 (LINK "Europe/Zurich" "Europe/Vaduz") (LINK "Europe/Rome" "Europe/Vatican")
 (LINK "Europe/Belgrade" "Europe/Zagreb")
 (LINK "Africa/Nairobi" "Indian/Antananarivo")
 (LINK "Asia/Bangkok" "Indian/Christmas") (LINK "Asia/Yangon" "Indian/Cocos")
 (LINK "Africa/Nairobi" "Indian/Comoro")
 (LINK "Indian/Maldives" "Indian/Kerguelen") (LINK "Asia/Dubai" "Indian/Mahe")
 (LINK "Africa/Nairobi" "Indian/Mayotte") (LINK "Asia/Dubai" "Indian/Reunion")
 (LINK "Pacific/Port_Moresby" "Pacific/Chuuk")
 (LINK "Pacific/Tarawa" "Pacific/Funafuti")
 (LINK "Pacific/Tarawa" "Pacific/Majuro")
 (LINK "Pacific/Pago_Pago" "Pacific/Midway")
 (LINK "Pacific/Guadalcanal" "Pacific/Pohnpei")
 (LINK "Pacific/Guam" "Pacific/Saipan") (LINK "Pacific/Tarawa" "Pacific/Wake")
 (LINK "Pacific/Tarawa" "Pacific/Wallis")
 (LINK "Africa/Abidjan" "Africa/Timbuktu")
 (LINK "America/Argentina/Catamarca" "America/Argentina/ComodRivadavia")
 (LINK "America/Adak" "America/Atka")
 (LINK "America/Panama" "America/Coral_Harbour")
 (LINK "America/Tijuana" "America/Ensenada")
 (LINK "America/Indiana/Indianapolis" "America/Fort_Wayne")
 (LINK "America/Toronto" "America/Montreal")
 (LINK "America/Toronto" "America/Nipigon")
 (LINK "America/Iqaluit" "America/Pangnirtung")
 (LINK "America/Rio_Branco" "America/Porto_Acre")
 (LINK "America/Winnipeg" "America/Rainy_River")
 (LINK "America/Argentina/Cordoba" "America/Rosario")
 (LINK "America/Tijuana" "America/Santa_Isabel")
 (LINK "America/Denver" "America/Shiprock")
 (LINK "America/Toronto" "America/Thunder_Bay")
 (LINK "America/Edmonton" "America/Yellowknife")
 (LINK "Pacific/Auckland" "Antarctica/South_Pole")
 (LINK "Asia/Ulaanbaatar" "Asia/Choibalsan")
 (LINK "Asia/Shanghai" "Asia/Chongqing") (LINK "Asia/Shanghai" "Asia/Harbin")
 (LINK "Asia/Urumqi" "Asia/Kashgar") (LINK "Asia/Jerusalem" "Asia/Tel_Aviv")
 (LINK "Europe/Berlin" "Atlantic/Jan_Mayen")
 (LINK "Australia/Sydney" "Australia/Canberra")
 (LINK "Australia/Hobart" "Australia/Currie")
 (LINK "Europe/London" "Europe/Belfast")
 (LINK "Europe/Chisinau" "Europe/Tiraspol")
 (LINK "Europe/Kyiv" "Europe/Uzhgorod")
 (LINK "Europe/Kyiv" "Europe/Zaporozhye")
 (LINK "Pacific/Kanton" "Pacific/Enderbury")
 (LINK "Pacific/Honolulu" "Pacific/Johnston")
 (LINK "Pacific/Port_Moresby" "Pacific/Yap") (LINK "Europe/Lisbon" "WET")
 (LINK "Africa/Nairobi" "Africa/Asmera")
 (LINK "America/Nuuk" "America/Godthab")
 (LINK "Asia/Ashgabat" "Asia/Ashkhabad") (LINK "Asia/Kolkata" "Asia/Calcutta")
 (LINK "Asia/Shanghai" "Asia/Chungking") (LINK "Asia/Dhaka" "Asia/Dacca")
 (LINK "Europe/Istanbul" "Asia/Istanbul")
 (LINK "Asia/Kathmandu" "Asia/Katmandu") (LINK "Asia/Macau" "Asia/Macao")
 (LINK "Asia/Yangon" "Asia/Rangoon") (LINK "Asia/Ho_Chi_Minh" "Asia/Saigon")
 (LINK "Asia/Thimphu" "Asia/Thimbu")
 (LINK "Asia/Makassar" "Asia/Ujung_Pandang")
 (LINK "Asia/Ulaanbaatar" "Asia/Ulan_Bator")
 (LINK "Atlantic/Faroe" "Atlantic/Faeroe") (LINK "Europe/Kyiv" "Europe/Kiev")
 (LINK "Asia/Nicosia" "Europe/Nicosia") (LINK "Pacific/Honolulu" "HST")
 (LINK "America/Los_Angeles" "PST8PDT")
 (LINK "Pacific/Guadalcanal" "Pacific/Ponape")
 (LINK "Pacific/Port_Moresby" "Pacific/Truk"))
