name: CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.org'
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  test:
    name: ${{ matrix.lisp }} / ${{ matrix.quicklisp-dist }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        lisp: [sbcl-bin, ccl-bin/1.12.2, ecl/24.5.10]
        os: [ubuntu-latest, windows-latest, macos-latest]
        quicklisp-dist:
          - quicklisp
          - ultralisp
        exclude:
          - os: windows-latest
            lisp: ecl/24.5.10
          - os: windows-latest
            lisp: ccl-bin/1.12.2
    env:
      LISP: ${{ matrix.lisp }}
      QUICKLISP_DIST: ${{ matrix.quicklisp-dist }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup Lisp
        continue-on-error: true
        uses: 40ants/setup-lisp@v4
        with:
          qlfile-template: |
            {% ifequal quicklisp_dist "ultralisp" %}
            dist ultralisp http://dist.ultralisp.org
            {% endifequal %}

      - name: Run tests (Non-Windows)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          ros install neil-lindquist/ci-utils
          asdf-register-project
          ros run --eval '(ql:quickload :zoneinfo/make-dist)' --eval '(progn (zoneinfo-dist:make-dist) (uiop:quit))'
          run-fiveam -e t -l zoneinfo/test :zoneinfo

      - name: Run tests (Windows)
        if: runner.os == 'Windows'
        shell: msys2 {0}
        run: |
          ros install neil-lindquist/ci-utils
          asdf-register-project
          ros run --eval '(ql:quickload :zoneinfo/make-dist)' --eval '(progn (zoneinfo-dist:make-dist) (uiop:quit))'
          run-fiveam -e t -l zoneinfo/test :zoneinfo
